version: "3.7"
services: 
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - 33069:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'prueba'
      MYSQL_USER: 'lajy'
      MYSQL_PASSWORD: 'Zamael1211!!'
      MYSQL_ROOT_PASSWORD: 'Zamael1211!!'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel: